name: Unit Tests

on:
  push:

  workflow_dispatch:


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ssciwr/doxygen-install@v1
      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true

      - name: Configure
        run: cmake --preset native

      - name: Build tests
        run: cmake --build --preset ut

      - name: Test
        run: ctest --preset ut

      - name: Build documentation
        run: cmake --build --preset documentation

      - name: Test installation
        run: cmake --build --preset install
        

